name: Scheduled deployments

on:
  schedule:
    - cron: '0 18 * * 5' # Friday at 18:00
      timezone: Europe/Helsinki
    - cron: '0 4 * * 1' # Monday at 04:00
      timezone: Europe/Helsinki

permissions:
  contents: write

concurrency:
  group: github-pages-deployment
  cancel-in-progress: false

jobs:
  deploy-dynamic:
    if: ${{ github.event.schedule == '0 18 * * 5' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Deploy dynamic site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          npm run deploy:dynamic -- -u "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

  deploy-static:
    if: ${{ github.event.schedule == '0 4 * * 1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Deploy static site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          npm run deploy:static -- -u "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
